### ISSUE TITLE
Additional MIDI tunes for further testing possibilities?

### ISSUE THREAD

**Issue by mxmilkiib** [x42/midigen.lv2#2]
Specific thoughts I have had;

* Note sweep but without the very lowest and highest octaves, as some synth patches don't make much sound on such notes.
* A tune properly utilising General MIDI instrumentation.
* A track that has just a basic General MIDI drums pattern (or a series of drum patterns just to mix it up).
* Note length testing arpeggio pattern with notes progressing from staccato to legato.
* Maybe something approaching [Black MIDI](https://en.wikipedia.org/wiki/Black_MIDI)?
* I made a wee request to Benn Jordan in the comments of their Duo X vid for an original [composition](https://theflashbulb.bandcamp.com/album/compositions-for-piano), so ¯\\\_(ツ)\_/¯

**Comment by x42** [comment]
I'm not sure about (1) the limited range note sweep. The intention of that is find synths that don't cover the complete range. Do you think it's really needed, it's not that long a wait.

(2) is now taken care of.  Soon fate will knock on every synth :)

Could you suggest .mid file that could be used for the others?

**Comment by x42** [comment]
for (5) I've opted for https://youtu.be/z7Q7v_QSCyw  

For good measure added some simple sequences that just trigger all 128 notes on a single MIDI channel at the same time  and another one: 256 notes over all 16 channels.  In theory there could be up to 128*16 concurrent notes, but likely no synth supports that polyphony. Also it'd take 2 seconds to transmit that single hit over a physical MIDI cable.

**Comment by mxmilkiib** [comment]
Sometimes, especially with a softer patch, the sweep felt like it was inaudible almost half the time.

**Comment by mxmilkiib** [comment]
I have found https://github.com/montoyamoraga/drum-machine-patterns

Edit: and also: https://github.com/JulianHMonk/Pattern2MIDI

**Comment by x42** [comment]
Nice find. I chose to first add the mandatory  https://en.wikipedia.org/wiki/Amen_break :)

**Comment by x42** [comment]
> Sometimes, especially with a softer patch, the sweep felt like it was inaudible almost half the time.

I first considered the grand piano range:  A0 (27.5Hz, midi-note 21) ... C8 (4.1kHz, midi-note 109). While that is an established range, it is still over 8 octaves and you might just audition all notes while you're at it.

How about the 6 octaves in the middle:  C1 (32 Hz, midi-note: 24) .. C7 (2KHz, midi-note: 96) as subset?

What do you think?

**Comment by x42** [comment]
Now up to 16 sequences, which should satisfy all the suggestions.

Let me know if that works for you or you have further suggestions. I think I'll close this issue. If a  Benn Jordan composition arrives - which would be very cool - this can be can be handled separately.
