### ISSUE TITLE
Send kill all notes on sequence change?

### ISSUE THREAD

**Issue by mxmilkiib** [x42/midigen.lv2#3]
Sometimes one or more notes left hanging on when the sequence is changed abruptly.

**Comment by x42** [comment]
There is already a panic message.

**Comment by x42** [comment]
Which synth and which host are you testing?  MIDI panic are a lot of concurrent messages, perhaps some of them are lost on the way?

**Comment by mxmilkiib** [comment]
Ah, then I guess my hearing held notes would be due to the MOD MIDI to CV Poly plugin, thanks.

**Comment by falkTX** [comment]
So it is not a all-notes-off but a different event?

**Comment by x42** [comment]
for each channel { raise pedal, all notes off } ;  the plugin does not send a "all sound off" message.

https://github.com/x42/midigen.lv2/blob/82a79c0cd3f020de4d3ac2255886c494d8a0bf9a/src/midigen.c#L100-L127
